version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/waste-record-management
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: pipelines/integrations-deployment-pre-post.sh
