# Generated by Django 4.2.2 on 2023-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('person_number', models.CharField(max_length=20)),
                ('register_no', models.CharField(max_length=50)),
                ('branches', models.CharField(choices=[('Branches', 'Branches'), ('Branches', 'Branches'), ('Branches Name', 'Branches Name')], max_length=50)),
                ('vat_no', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
