# Generated by Django 4.2.2 on 2023-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2)),
                ('entry_date', models.DateField(max_length=20)),
                ('manifest_no', models.CharField(max_length=255)),
                ('disposal_slip_no', models.CharField(max_length=50)),
                ('vehicle_registration', models.CharField(max_length=20)),
                ('bin_size', models.CharField(max_length=50)),
                ('bin_GW', models.CharField(max_length=50)),
                ('land_fill', models.CharField(choices=[('1-C', '1-C'), ('2-C', '2-C'), ('3-C', '3-C')], max_length=50)),
                ('recyclable_item', models.CharField(choices=[('1-C', '1-C'), ('2-C', '2-C'), ('3-C', '3-C')], max_length=50)),
                ('solid_waste', models.CharField(max_length=50)),
                ('liquid_waste', models.CharField(max_length=50)),
                ('hazardous_waste', models.CharField(max_length=50)),
                ('rubble', models.CharField(max_length=50)),
                ('total_waste', models.CharField(max_length=50)),
                ('collection_note', models.FileField(upload_to='doc/')),
                ('service_provider_certificate', models.FileField(upload_to='doc/')),
                ('landfill_disposal_certificate', models.FileField(upload_to='doc/')),
                ('lab_test_result', models.FileField(upload_to='doc/')),
                ('weightbridge_certificate', models.FileField(upload_to='doc/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='branches',
            field=models.CharField(choices=[('1-C', '1-C'), ('2-C', '2-C'), ('3-C', '3-C')], max_length=50),
        ),
    ]
