# Generated by Django 4.2.2 on 2023-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_wasterecord_user_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterecord',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='branches',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
