# Generated by Django 4.2.2 on 2023-06-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_wasterecord_alter_company_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(choices=[('1-C', '1-C'), ('2-C', '2-C'), ('3-C', '3-C')], max_length=50)),
                ('id_no', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=50)),
                ('employment_start', models.DateField(max_length=20)),
                ('employment_end', models.DateField(max_length=20)),
                ('race', models.CharField(choices=[('1', 'Race1'), ('2', 'Race2'), ('3', 'Race3')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='wasterecord',
            old_name='weightbridge_certificate',
            new_name='weight_bridge_certificate',
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='land_fill',
            field=models.CharField(choices=[('1', 'LandFill1'), ('2', 'LandFill2'), ('3', 'LandFill3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='recyclable_item',
            field=models.CharField(choices=[('1', 'item1'), ('2', 'item2'), ('3', 'item3')], max_length=50),
        ),
    ]
