# Generated by Django 4.2.2 on 2023-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_wasterecord_branch_alter_company_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('file', models.CharField(max_length=255)),
            ],
        ),
    ]
