# Generated by Django 4.2.2 on 2023-08-22 13:02

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=master.models.complalience_certificates),
        ),
    ]
