# Generated by Django 4.2.2 on 2023-09-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='land_fill',
            field=models.CharField(max_length=50),
        ),
    ]
