# Generated by Django 4.2.2 on 2023-09-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_wasterecord_land_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterecord',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
